dependencies:
 - python=3.8
 - rdkit
 - pip
 - pip:
     - setuptools
     - numpy
     - Cython
     - wheel
     - pandas
     - aicrowd_api
     - scikit-learn
     - py4j
     - tensorflow
     - keras
