dependencies:
 - python==3.6
 - pip
 - pip:
     - setuptools
     - numpy
     - Cython
     - wheel
     - pandas==0.25.3
     - aicrowd_api
     - scikit-learn
     - py4j
     - tensorflow
     - keras
     - CGRtools
